print('World Shop')
print('list')
print('-----------------')
print('Egg : 5 Bath')
print('Prok : 150 Bath')
print('Meat : 250 Bath')
print('Fish : 120 Bath')
print('Apple : 10 Bath')
print('Mango : 15 Bath')
print('Durian : 50 Bath')
print('-----------------')
print('End')
